phrase_categories = {
    "individualising": {
        "color": "#fffa65",
        "phrases": [
            # Direct address and pronouns
            "you", "your", "you're", "yours", "yourself", "yourselves", "you all", "you guys", "ur", "u", "one of you",
            # Modal verbs, imperatives, encouragement
            "you should", "you must", "you have to", "you need to", "you can", "you could", "you might", "you ought to", "you better", "you are required to", "you are expected to", "you are supposed to", "you are empowered to", "you are able to",
            # Responsibility, guilt, agency
            "your responsibility", "your duty", "your obligation", "it's up to you", "if you", "if only you", "if you would", "if you could", "if you try", "if you act", "if you decide", "if you choose", "if you make better choices", "if you make a difference",
            "it's your fault", "you caused", "you made", "you did", "you created", "you allowed", "you triggered", "you led to", "you are responsible", "you should consider", "you ought to", "you have the power", "you are the reason", "you are the solution", "you are the problem", "you are the change",
            # Actions, choices, lifestyle
            "your actions", "your choices", "your behaviour", "your decisions", "your lifestyle", "your impact", "your contribution", "your footprint", "your carbon footprint", "your plastic use", "your consumption", "your habits", "your waste", "your emissions", "your travel", "your commute", "your recycling", "your energy use", "your food choices", "your daily routine", "your influence", "your example", "your leadership", "your small steps",
            "change your habits", "change your lifestyle", "improve your choices", "reduce your impact", "minimize your waste", "adopt sustainable habits", "adopt green habits", "be responsible", "do your part", "play your part", "make a difference", "take action", "step up", "do better", "lead by example", "set an example", "shift your mindset", "do more", "do less", "act now", "don't wait", "start today", "start now", "take the first step", "make a start",
            # Appeals to the individual
            "every individual", "each person", "personal responsibility", "personally responsible", "one person at a time", "it starts with you", "it begins with you", "it depends on you", "be the change", "be a change maker", "be a leader", "be an example", "be proactive", "be accountable", "take ownership", "take charge", "take initiative", "make it happen", "your initiative",
            # Self-reference (I/my)
            "my responsibility", "my duty", "my actions", "my choices", "my impact", "my contribution", "my habits", "my lifestyle", "my example", "my decision", "my behaviour", "my choices matter", "my impact matters", "I should", "I must", "I have to", "I need to", "I can", "I could", "I might", "I am responsible", "I was wrong", "I am trying", "I am working on it", "I will", "I promise", "I commit", "I choose to", "I want to", "I intend to", "I strive to", "I hope to", "I plan to", "I will make a difference", "I pledge", "I will try", "I care", "my future", "my children", "my grandchildren", "my legacy", "I am the change", "I make a difference", "I take action", "I lead by example", "I start now", "I begin today", "I feel responsible", "I am accountable",
            # Individual guilt or pride
            "I feel guilty", "I feel ashamed", "I am proud", "I am ashamed", "I am trying", "I am working on it", "I am making progress", "I am learning", "I am improving", "I regret", "I wish I had", "I wish I could", "I wish I would", "I wish I did", "I could have done more", "I should have done more",
            # Miscellaneous
            "make your mark", "leave your mark", "your legacy", "your future", "your children's future", "your grandchildren's future", "your place in history", "your influence matters", "your actions count", "your voice matters", "your vote matters", "your participation", "your engagement"
        ]
    },
    "collective_we": {
        "color": "#8ad6ff",
        "phrases": [
            # Pronouns and collective address
            "we", "we're", "we are", "we have", "we need", "we must", "we should", "we can", "we will", "we won't", "we've", "we'll", "we can't", "we could", "we might", "us", "our", "ours", "ourselves", "all of us", "each of us", "every one of us", "everyone", "everybody", "as people", "as humans", "as citizens", "as a team", "as a family", "as a community", "as a society", "as a group", "as a nation", "as a people", "as a species", "as a civilization", "as one", "as one people", "as one world", "as one planet", "in unity", "united", "united we stand", "joined together", "shoulder to shoulder", "hand in hand", "side by side", "band together",
            # Collective responsibility and calls to action
            "we're messing up", "we're ruining", "we're destroying", "we're failing", "we're responsible", "we're all in this together", "together we", "together we can", "together we will", "together we must", "together we act", "together for the planet", "together for the earth", "let's", "let us", "let's act", "let's change", "let's make a difference", "let's do this", "let's begin", "let's work together", "let's unite", "let's all", "let's come together", "if we", "when we", "should we", "can we", "must we", "collective responsibility", "shared responsibility", "shared duty", "shared obligation", "shared burden", "shared future", "common responsibility", "joint responsibility", "joint effort", "common effort", "collective effort", "collaborative effort", "united effort", "group effort", "our duty", "our obligation", "our role", "our mission", "our shared future", "our shared planet", "our shared home",
            "we must act", "we should act", "we can make a difference", "we all have a part to play", "we all have a role", "we share responsibility", "we share this planet", "we share this earth", "we have the power", "we can solve", "we can fix", "we can improve", "we can help", "we can change", "we can do better", "we need change", "we need to act", "we must change", "we must act", "we should change", "we should help", "we are the solution", "we are the problem", "we are all responsible", "we all benefit", "we all suffer", "we all lose", "we all win", "we all gain", "for all of us", "for everyone", "for people everywhere", "for the good of all", "for the greater good", "for future generations", "for humanity", "for the next generation", "for people and planet", "for us all", "for the benefit of all", "for society as a whole", "for the world", "for the earth", "for nature", "for the environment",
            # Our world, our environment, our future
            "our planet", "our world", "our earth", "our environment", "our actions", "our choices", "our future", "our children", "our grandchildren", "our legacy", "our descendants", "our home", "our only home", "our common home", "our resources", "our health", "our water", "our air", "our land", "our forests", "our oceans", "our wildlife", "our biodiversity", "our climate", "our atmosphere", "our ecosystem", "our energy", "our food", "our farms", "our cities", "our communities", "our families", "our neighborhoods", "our streets", "our schools", "our workplaces",
            # Collective appeals and slogans
            "it’s up to us", "it’s our duty", "it’s our obligation", "we cannot ignore", "we cannot wait", "we cannot afford to", "we are running out of time", "now is our time", "now is the time", "for the sake of us all", "for all living things", "for all beings", "for the world we share", "for the planet we love", "for the place we call home", "for every generation", "for every species", "for all life on earth", "for life on earth", "for earth’s future", "for the future of humanity", "for all people", "for all children", "for every child", "for the sake of our future", "for the sake of humanity", "for the sake of the world", "for a better world", "for a better future", "for a cleaner planet", "for a safer planet", "for a healthier world", "for a thriving planet", "for a living planet", "for a flourishing earth", "for a hopeful future"
        ]
    },
    "greenwashing": {
        "color": "#b0ffb0",
        "phrases": [
            # Eco and green language
            "natural", "nature", "nature's", "healthy", "healthier planet", "healthy planet", "sustainable", "eco-friendly", "environmentally friendly", "environment-friendly", "green", "planet-friendly", "earth-friendly", "green label", "green product", "green brand", "green company", "green business", "green initiative", "green movement", "green living", "green alternative", "green packaging", "green technology", "green solution", "green innovation", "green energy", "green economy", "green jobs", "green future", "greenwashing", "greenwashed", "green claims",
            # Responsibility, sourcing, and purity
            "responsibly sourced", "ethically sourced", "locally sourced", "sustainably sourced", "sustainably made", "sustainably farmed", "sustainably grown", "sustainably harvested", "organic", "pure", "all-natural", "100% natural", "clean", "clean energy", "clean label", "clean product", "clean water", "clean air", "clean technology", "clean innovation", "clean future", "pure ingredients", "pure water", "pure air", "non-toxic", "safe for the environment", "safe for the planet",
            # Climate claims, metrics, and promises
            "carbon neutral", "net zero", "carbon negative", "climate positive", "climate neutral", "carbon offset", "carbon offsets", "carbon free", "carbon conscious", "carbon smart", "carbon friendly", "climate solution", "climate smart", "climate friendly", "climate aware", "climate action", "climate safe", "climate responsible", "climate commitment", "carbon balanced", "zero carbon", "zero emissions", "net-zero emissions", "low carbon", "reduced emissions", "offsetting emissions", "emissions free", "zero waste",
            # Circularity, waste, recyclability
            "biodegradable", "compostable", "recyclable", "recycled content", "recycled materials", "recycled packaging", "recycled plastic", "recycled paper", "upcycled", "circular", "circular economy", "cradle to cradle", "waste-free", "minimal waste", "minimal impact", "leave no trace", "zero landfill", "plastic-free", "plastic neutral", "reusable", "refillable", "reusable packaging", "refill station", "reduced packaging", "minimal packaging", "responsible packaging",
            # Lifestyle, image, and aspirational terms
            "environmentally safe", "environmentally sound", "environmentally conscious", "environmentally aware", "planet safe", "planet care", "planet safe", "earth safe", "earth care", "future friendly", "clean future", "green future", "greener choice", "eco packaging", "eco design", "eco solutions", "eco innovation", "eco technology", "eco tech", "eco conscious", "eco aware", "future proof", "planet loving", "earth loving", "planet first", "earth first", "planet positive", "earth positive", "planet inspired", "sustainably designed", "planet driven", "eco-driven", "nature inspired", "planet inspired", "nature based", "nature derived", "planet safe", "earth positive", "earth friendly", "eco label", "eco-label", "eco certification", "B Corp", "environmentally superior", "doing good", "for the planet", "for the earth", "for nature", "for the environment", "good for the planet", "good for nature", "good for the environment", "planet smart", "planet solution", "planet safe", "planet care", "planet commitment", "planet focus", "planet promise", "save the planet", "saving the planet", "protecting the earth", "better for the environment", "make a difference for the planet", "help the planet", "support the planet"
        ]
    },
    "moral_metaphors": {
        "color": "#ffb0b0",
        "phrases": [
            # Planet as person, family, home, etc
            "no planet B", "no plan B", "mother nature", "mother earth", "earth is hurting", "earth is crying", "the earth is suffering", "nature is crying", "planet in crisis", "planet in peril", "the earth needs us", "planet needs saving", "planet needs our help", "planet is suffering", "planet is a victim", "earth as our home", "planet as a family", "planet as a child", "planet as a mother", "planet as a parent", "planet as a living being", "earth as a living being", "earth as a mother", "planet is sick", "planet is dying", "planet is calling", "nature calls", "nature cries out", "the land cries", "the land suffers", "the land remembers", "the land will judge us", "the earth will judge us", "the planet will judge us", "the earth is our mother", "the earth is our family", "planet as our child", "earth as our child", "planet as our future", "planet as a gift", "planet is our gift", "gift to protect", "nurture the planet", "nurture mother earth", "care for mother earth",
            # Generational, legacy, stewardship
            "future generations", "the next generation", "our children", "our grandchildren", "our legacy", "our descendants", "our inheritance", "inheritance", "be a good ancestor", "for the sake of our children", "for the sake of our grandchildren", "for the sake of the planet", "protect our legacy", "protect our future", "preserve our future", "preserve their future", "protect their future", "the world we leave behind", "what we leave behind", "leave a legacy", "leave a mark", "leave a better world", "our only home", "our common home", "planet is our home", "earth is our home", "home for humanity", "home for all", "our shared home", "our shared future", "our collective destiny", "our fate is tied to the earth", "our fate is tied to the planet",
            # Duty, morality, justice, and obligation
            "stewardship", "be a steward", "be stewards", "moral duty", "moral imperative", "ethical obligation", "ethical responsibility", "the right thing to do", "do your bit", "do the right thing", "stand up for the planet", "defend the earth", "save our home", "heal the planet", "guardian of nature", "guardian of earth", "earth’s guardians", "planet’s guardians", "planet as a victim", "earth is our responsibility", "planet is counting on us", "planet at risk", "planet in need", "planet needs us", "planet needs protection", "planet needs defending", "planet needs healing", "answer the call", "answer nature’s call", "rise to the challenge", "rise to the occasion", "rise for the earth", "stand up for the earth", "stand for the planet", "do what’s right", "do what is right", "do what matters", "the right side of history", "right side of history", "for the sake of humanity", "for the sake of the world", "for the sake of earth", "a debt to the earth", "a debt to the planet", "planetary justice", "environmental justice", "cosmic justice", "cosmic duty", "a higher calling", "a sacred trust", "sacred responsibility", "sacred duty", "planet as our destiny", "earth is our destiny", "planet is our heirloom", "planet is our inheritance", "earth is our legacy", "planet is our destiny", "planet will remember", "nature will remember", "the land remembers", "earth never forgets", "nature never forgets", "nature forgives", "nature punishes", "nature heals", "nature will heal", "planet is our heirloom",
            # Hope, inspiration, calls to action
            "be the change", "be a force for good", "be a guardian", "be a protector", "protect what matters", "protect what is precious", "defend what is precious", "stand for what is right", "stand up for what is right", "fight for the future", "fight for tomorrow", "fight for a better world", "heal the earth", "heal the planet", "heal our home", "save the planet", "save our home", "save the earth", "save our future", "save our legacy", "save tomorrow", "for tomorrow", "for the future", "for tomorrow’s children", "for tomorrow’s generations", "for all living things", "for all beings", "for all life on earth", "for life on earth", "for earth’s future", "for the future of humanity"
        ]
    }
}
